import assert from "node:assert/strict";
import test from "node:test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { buildDiagramModel } from "@/lib/diagram/model";
import { mermaidMarkdown, renderMermaid } from "@/lib/diagram/mermaid";
import { defaultDiagramOptions } from "@/lib/diagram/options";
import { loop, makeResult, many, webApp } from "./fixtures";

const ORIGIN = "https://cartograph.test";
const options = defaultDiagramOptions("document");

test("mermaid has the same units, groups, and weighted edges as the model", () => {
  const model = buildDiagramModel(webApp(), options);
  const mermaid = renderMermaid(model, ORIGIN);
  assert.match(mermaid, /^%% Generated by Cartograph/);
  assert.match(mermaid, /\nflowchart LR\n/);
  assert.match(mermaid, /subgraph g_lib\["lib"\]/);
  for (const edge of model.edges) {
    const arrow = edge.count >= 2 ? `-->|${edge.count}|` : "-->";
    assert.ok(mermaid.includes(arrow), `missing ${edge.id}`);
  }
  assert.equal((mermaid.match(/-->|-\.->/g) ?? []).length, model.edges.length);
});

test("ids are sanitized and collisions get suffixes", () => {
  const model = buildDiagramModel(makeResult({ ...many("a-b", 3), ...many("a_b", 3, ["a-b/f00.ts"]) }), { ...options, detail: "overview" });
  const mermaid = renderMermaid(model, ORIGIN);
  assert.match(mermaid, /u_a_b\["a-b<br\/>/);
  assert.match(mermaid, /u_a_b_2\["a_b<br\/>/);
});

test("labels cannot break the syntax", () => {
  const model = buildDiagramModel(makeResult({ ...many('x"<y>`', 3) }), { ...options, detail: "overview" });
  const mermaid = renderMermaid(model, ORIGIN);
  assert.match(mermaid, /\["x#quot;y<br\/>/);
});

test("only mutual imports mark a cycle class", () => {
  const cyclic = renderMermaid(buildDiagramModel(loop(), options), ORIGIN);
  assert.match(cyclic, /class u_a,u_b cycle/);
  const plain = renderMermaid(buildDiagramModel(webApp(), options), ORIGIN);
  assert.doesNotMatch(plain, /^\s*class .* cycle$/m);
});

test("markdown wraps the block and credits the source", () => {
  const markdown = mermaidMarkdown("flowchart LR", "https://cartograph.test/repo/1");
  assert.equal(markdown, "```mermaid\nflowchart LR\n```\n\n<sub>Generated by [Cartograph](https://cartograph.test/repo/1) · verified from import statements</sub>\n");
});

test("golden: webapp.mmd", () => {
  const mermaid = renderMermaid(buildDiagramModel(webApp(), options), ORIGIN);
  const file = path.join(process.cwd(), "tests", "diagram", "golden", "webapp.mmd");
  if (process.env.UPDATE_GOLDEN === "1") {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, mermaid);
  }
  assert.equal(mermaid, readFileSync(file, "utf8"));
});
