import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { layoutDiagram } from "@/lib/diagram/layout";
import { buildDiagramModel } from "@/lib/diagram/model";
import { defaultDiagramOptions } from "@/lib/diagram/options";
import { renderSvg } from "@/lib/diagram/svg";
import type { DiagramOptions, DiagramReviewAnnotations } from "@/lib/diagram/types";
import { makeResult, many, webApp } from "./fixtures";

const NONE: DiagramReviewAnnotations = { captions: new Map(), notes: [] };
const ORIGIN = "https://cartograph.test";

async function render(result = webApp(), over: Partial<DiagramOptions> = {}, annotations = NONE, embedFonts = false) {
  const options = { ...defaultDiagramOptions(over.preset ?? "document"), ...over };
  const positioned = await layoutDiagram(buildDiagramModel(result, options), options);
  return renderSvg({ positioned, options, annotations, origin: ORIGIN, embedFonts });
}

// Includes text inside <tspan>s (captions, note tags), with the inner tags stripped.
const drawnText = (svg: string) =>
  [...svg.matchAll(/<text[^>]*>(.*?)<\/text>/g)].map((match) => match[1].replace(/<[^>]+>/g, "")).join("");

test("the SVG is byte-identical across renders", async () => {
  assert.equal((await render()).svg, (await render()).svg);
});

test("the SVG is self-contained, titled, and sized", async () => {
  const { svg, width, height } = await render();
  assert.match(svg, /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg"/);
  assert.match(svg, new RegExp(`viewBox="0 0 ${width} ${height}"`));
  assert.match(svg, /<title id="t">fixture<\/title>/);
  assert.doesNotMatch(svg, /href="(?!#)/);
  assert.doesNotMatch(svg, /<image|<script|<foreignObject/);
  assert.ok(width >= 960 && width <= 2400);
});

test("slides are exactly 1920 by 1080", async () => {
  const { width, height } = await render(webApp(), { preset: "slide" });
  assert.deepEqual([width, height], [1920, 1080]);
});

test("hostile names are escaped", async () => {
  const result = makeResult({ ...many("a<b>&\"'", 3), ...many("ok", 3, ["a<b>&\"'/f00.ts"]) });
  const { svg } = await render(result);
  assert.doesNotMatch(svg, /a<b>/);
  assert.match(svg, /a&lt;b&gt;&amp;&quot;&#39;/);
});

test("drawn text only uses characters the embedded Latin fonts contain", async () => {
  const result = makeResult({ ...many("日本", 3), ...many("ok", 3, ["日本/f00.ts"]) });
  const annotations: DiagramReviewAnnotations = {
    captions: new Map([["u:ok", "Checkout → payments"]]),
    notes: [{ text: "A → B ① ⟲", subjects: ["u:ok"], source: "ai" }],
  };
  const { svg } = await render(result, { annotations: "measured+ai" }, annotations);
  for (const char of drawnText(svg.replace(/&[a-z#0-9]+;/g, "&"))) {
    const code = char.codePointAt(0)!;
    assert.ok((code >= 0x20 && code <= 0xff) || (code >= 0x2000 && code <= 0x206f), `U+${code.toString(16)} "${char}" is outside the Latin subset`);
  }
});

test("captions never move a unit", async () => {
  const withCaptions: DiagramReviewAnnotations = { captions: new Map([["u:app", "Web entry points"]]), notes: [] };
  const a = await render(webApp(), { annotations: "measured+ai" }, NONE);
  const b = await render(webApp(), { annotations: "measured+ai" }, withCaptions);
  const rects = (svg: string) => [...svg.matchAll(/<rect class="unit"[^>]*>/g)].map((match) => match[0]);
  assert.deepEqual(rects(a.svg), rects(b.svg));
  assert.match(b.svg, /Web entry points/);
  assert.match(b.svg, /generated caption, not measured/);
});

test("omissions and provenance are stated on the figure", async () => {
  const { svg } = await render();
  assert.match(svg, /Tests hidden \(3 files\)/);
  assert.match(svg, /Generated by Cartograph · verified from import statements/);
  assert.match(svg, /cartograph\.test\/repo\/00000000-0000-4000-8000-000000000000/);
});

test("analyses without IR and without edges still render with an explanation", async () => {
  const { svg } = await render(makeResult({ "a.ts": [] }));
  assert.match(svg, /No internal imports were found\./);
  assert.match(svg, /Partial evidence/);
});

test("measured findings become numbered notes", async () => {
  const result = makeResult({ ...many("a", 3, ["b/f00.ts"]), ...many("b", 3, ["a/f00.ts"]) });
  const { svg } = await render(result, { detail: "overview" }, {
    captions: new Map(),
    notes: [{ text: "a and b import each other.", subjects: ["u:a", "u:b"], source: "measured" }],
  });
  assert.match(svg, /a and b import each other\./);
  assert.match(svg, /class="note-marker"/);
});

test("fonts are embedded when requested", async () => {
  const { svg } = await render(webApp(), {}, NONE, true);
  assert.match(svg, /@font-face\{font-family:"IBM Plex Mono";font-weight:400;font-style:normal;src:url\(data:font\/woff2;base64,/);
  assert.ok(Buffer.byteLength(svg) < 200_000, `SVG is ${Buffer.byteLength(svg)} bytes`);
});

for (const [name, over] of [
  ["webapp-document-light", {}],
  ["webapp-slide-dark", { preset: "slide", theme: "dark" }],
  ["webapp-overview-print", { detail: "overview", theme: "print" }],
] as const) {
  test(`golden: ${name}`, async () => {
    const { svg } = await render(webApp(), over as Partial<DiagramOptions>);
    const file = path.join(process.cwd(), "tests", "diagram", "golden", `${name}.svg`);
    if (process.env.UPDATE_GOLDEN === "1") {
      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(file, svg);
    }
    assert.equal(svg, readFileSync(file, "utf8"), "run with UPDATE_GOLDEN=1 after reviewing the change");
  });
}

async function renderWith(over: (model: ReturnType<typeof buildDiagramModel>) => ReturnType<typeof buildDiagramModel>, preset: "document" | "slide" = "document") {
  const options = defaultDiagramOptions(preset);
  const model = over(buildDiagramModel(webApp(), options));
  const positioned = await layoutDiagram(model, options);
  return renderSvg({ positioned: { ...positioned, model }, options, annotations: NONE, origin: ORIGIN, embedFonts: false });
}

test("a long shared-parts list cannot push out Partial evidence; the list is capped", async () => {
  for (const preset of ["document", "slide"] as const) {
    const { svg, width, height } = await renderWith((model) => ({
      ...model,
      partialEvidence: true,
      omitted: { ...model.omitted, sharedEdges: 5 },
      units: model.units.map((unit, index) => ({ ...unit, sharedBy: 4, label: `shared-part-number-${index}` })),
    }), preset);
    assert.match(svg, /Partial evidence/);
    assert.match(svg, /\+\d+ more\) are not drawn/);
    if (preset === "slide") assert.deepEqual([width, height], [1920, 1080]);
  }
});

test("the weaker-connections clause is singular for one import", async () => {
  const one = await renderWith((model) => ({ ...model, omitted: { ...model.omitted, edges: 2, edgeMaxCount: 1 } }));
  assert.match(one.svg, /\(1 import each\)/);
  const many = await renderWith((model) => ({ ...model, omitted: { ...model.omitted, edges: 2, edgeMaxCount: 3 } }));
  assert.match(many.svg, /\(at most 3 imports each\)/);
});
