/**
 * Mermaid output, for diagrams that live as text in a README.
 *
 * Same model as the SVG, so the boxes, groups and counts match exactly.
 * Themes, size bars, notes and AI captions are left out: Mermaid cannot mark
 * generated text as generated, so it gets none.
 *
 * @module lib/diagram/mermaid
 */
import { unitMeta } from "./metrics";
import type { DiagramModel } from "./types";

const label = (value: string) => value.replace(/[\r\n]+/g, " ").replace(/[<>`]/g, "").replace(/"/g, "#quot;");

function assignIds(ids: ReadonlyArray<string>): Map<string, string> {
  const assigned = new Map<string, string>();
  const used = new Set<string>();
  // Code-unit order, not locale order: collision suffixes must not depend on ICU punctuation rules.
  for (const id of [...ids].sort()) {
    const base = id.replace(/[^A-Za-z0-9]/g, "_");
    let candidate = base;
    for (let n = 2; used.has(candidate); n += 1) candidate = `${base}_${n}`;
    used.add(candidate);
    assigned.set(id, candidate);
  }
  return assigned;
}

export function renderMermaid(model: DiagramModel, origin: string): string {
  const ids = assignIds([...model.groups.map((group) => group.id), ...model.units.map((unit) => unit.id)]);
  const lines = [
    `%% Generated by Cartograph from import statements. Analysis ${model.analysisId.slice(0, 8)} (${model.analyzedAt.slice(0, 10)}).`,
    `%% ${origin.replace(/\/$/, "")}/repo/${model.analysisId}`,
    "flowchart LR",
  ];
  const emit = (parentId: string | null, indent: string) => {
    for (const group of model.groups.filter((candidate) => candidate.parentId === parentId)) {
      lines.push(`${indent}subgraph ${ids.get(group.id)}["${label(group.label)}"]`);
      emit(group.id, `${indent}  `);
      lines.push(`${indent}end`);
    }
    for (const unit of model.units.filter((candidate) => candidate.groupId === parentId)) {
      lines.push(`${indent}${ids.get(unit.id)}["${label(unit.label)}<br/>${label(unitMeta(unit))}"]`);
    }
  };
  emit(null, "  ");
  for (const edge of model.edges) {
    const unresolved = edge.to === "u:#unresolved";
    const arrow = unresolved ? "-.->" : edge.count >= 2 ? `-->|${edge.count}|` : "-->";
    lines.push(`  ${ids.get(edge.from)} ${arrow} ${ids.get(edge.to)}`);
  }
  // Like the SVG, only mutual imports mark a cycle: units on one get the class.
  const mutualUnits = new Set(model.edges.filter((edge) => edge.mutual).flatMap((edge) => [edge.from, edge.to]));
  const cyclic = model.units.filter((unit) => mutualUnits.has(unit.id)).map((unit) => ids.get(unit.id));
  lines.push("  classDef cycle stroke:#7A5312,stroke-width:2px");
  lines.push("  classDef unresolved stroke-dasharray:4 4");
  if (cyclic.length > 0) lines.push(`  class ${cyclic.join(",")} cycle`);
  const unresolved = model.units.filter((unit) => unit.kind === "unresolved").map((unit) => ids.get(unit.id));
  if (unresolved.length > 0) lines.push(`  class ${unresolved.join(",")} unresolved`);
  return `${lines.join("\n")}\n`;
}

export function mermaidMarkdown(mermaid: string, shareUrl: string): string {
  return `\`\`\`mermaid\n${mermaid.trimEnd()}\n\`\`\`\n\n<sub>Generated by [Cartograph](${shareUrl}) · verified from import statements</sub>\n`;
}
